version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: morphin-db
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: morphin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: morphin-redis
    ports:
      - "6379:6379"
    networks:
      - backend

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development
    env_file:
      - .env.production
    volumes:
      - .:/usr/src/app
    command: npm run start
    expose:
      - "3000"
    deploy:
      replicas: 3
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
